### ISSUE TITLE
Crash on statistics when not enough data is present.

### ISSUE THREAD

**Issue by ghorwin** [projecthamster/experiments#24]
Applies to Version 2.91.3+git20120514.b9fec3e1-1ubuntu1 (Ubuntu 14.10 repo version)

Showing statistics after a fresh install crashes in show() with a list index out of bounds.

**Comment by tbaugis** [comment]
please file the bug in the appropriate project. hamster/experiments is an experimental sprite abstraction lib.

here's the project you are looking for:
https://github.com/projecthamster/hamster/issues
