### ISSUE TITLE
Textencoding (german umlaute) not properly done in HTML report

### ISSUE THREAD

**Issue by ghorwin** [projecthamster/experiments#25]
HTML report claims to use utf8 encoding, yet tags written with german umlaute (e.g. Präsentation) are encoded and not shown correctly.

**Comment by tbaugis** [comment]
please file the bug in the appropriate project. hamster/experiments is an experimental sprite abstraction lib.

here's the project you are looking for:
https://github.com/projecthamster/hamster/issues
